import os


# Get the folder of the top-level directory of this project
BASEDIR = os.path.abspath(os.path.dirname(__file__))

# Update later by using a random number generator and moving
# the actual key outside of the source code under version control
SECRET_KEY = 'justakey'
DEBUG = True

# SQLAlchemy
DATABASE_FILE = 'foodtracker.db'
