name: Deploy

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      # Specify some input for this particular action
      with:
        python-version: '3.8.6'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
    - name: Copying files through scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "~/test"
    - name: Did it work
      if: ${{ failure() }}
      run: echo "it worked" 