name: Deploy without ssh

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      # Specify some input for this particular action
      with:
        python-version: '3.8.6'
        run: |
          mkdir foodtracker
          python3 -m venv foodtracker/env
          source ./env/bin/activate
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
      if: success ()
    - name: Copy files
      run: |
        cp -r $GITHUB_WORKSPACE/ ~/foodtracker
    - name: Install everything
      run: |
        cd ~/foodtracker
        python3 -m venv env
        source ./env/bin/activate
        pip3 install -r requirements.txt
        sudo /bin/systemctl restart foodtracker.service
        ./check_running.sh
    - name: Done
      if: success()
      run: echo "Succes !! All done, enjoy"
