name: Deploy

on: workflow_dispatch

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      # Specify some input for this particular action
      with:
        python-version: '3.8.6'
        run: |
          mkdir foodtracker
          python3 -m venv foodtracker/env
          source ./env/bin/activate
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
      if: success ()
    - name: Copying files through scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "~/foodtracker"
      if: success()
    - name: Excecuting restart commands
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          python3 -m venv env
          source ./env/bin/activate
          pip3 install -r requirements.txt
          sudo /bin/systemctl restart foodtracker.service
    - name: Done
      if: success()
      run: echo "Succes !! All done, enjoy"
