name: Deploy through ssh

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
      if: success ()
    - name: Delete test db
      run: rm foodtracker.db
    - name: Copying files through scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "~/foodtracker"
      if: success()
    - name: Excecuting restart commands
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/foodtracker
          python3 -m venv env
          source ./env/bin/activate
          pip3 install -r requirements.txt
          sudo /bin/systemctl restart foodtracker.service
    - name: Done
      if: success()
      run: echo "Succes !! All done, let's clean up and enjoy"
